env:
  browser: true
  commonjs: true
  es6: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  # some times next variable is required on express even if it's not used just to specify certain handler functions. So we have to allow it
  no-unused-vars:
    [error, { argsIgnorePattern: next }]
  # ignore common mongo properties
  no-underscore-dangle:
    [error, { allow: ["_id", "__v"] }]
  max-len:
    # keep airbnb's 100 char's per code line but ignore the rule for comments and strings
    [error, { code: 100, ignoreComments: true, ignoreStrings: true, ignoreTemplateLiterals: true }]